/**
 * @file fonts_config.hpp
 * @brief Font Compilation Configuration — Auto-generated by FontHub Editor
 * @author LoveFinder
 */

#ifndef FONTS_CONFIG_HPP
#define FONTS_CONFIG_HPP

// ------------------------------------------------------------------
// FONT_STYLE1_7X10
// ------------------------------------------------------------------
#ifndef USE_FONT_STYLE1_7X10
#define USE_FONT_STYLE1_7X10    1
#endif

// ------------------------------------------------------------------
// FONT_STYLE1_11X18
// ------------------------------------------------------------------
#ifndef USE_FONT_STYLE1_11X18
#define USE_FONT_STYLE1_11X18    0
#endif

// ------------------------------------------------------------------
// FONT_STYLE1_16X26
// ------------------------------------------------------------------
#ifndef USE_FONT_STYLE1_16X26
#define USE_FONT_STYLE1_16X26    0
#endif

// ------------------------------------------------------------------
// FONT_STYLE2_9X18
// ------------------------------------------------------------------
#ifndef USE_FONT_STYLE2_9X18
#define USE_FONT_STYLE2_9X18    1
#endif

// ------------------------------------------------------------------
// FONT_STYLE3_ZH
// ------------------------------------------------------------------
#ifndef USE_FONT_STYLE3_ZH_16X16
#define USE_FONT_STYLE3_ZH_16X16    1
#endif

// ------------------------------------------------------------------
// STYLE1_7X10
// ------------------------------------------------------------------
#ifndef USE_STYLE1_7X10
#define USE_STYLE1_7X10    1
#endif

// ------------------------------------------------------------------
// STYLE2_9X18
// ------------------------------------------------------------------
#ifndef USE_STYLE2_9X18
#define USE_STYLE2_9X18    1
#endif

#endif // FONTS_CONFIG_HPP
